-- AUTO-GENERATED DEFINITION
DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST
(
    id       INT NOT NULL
        PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(20) NULL,
    sex      VARCHAR(6) NULL,
    birthday DATE NULL,
    address  VARCHAR(20) NULL,
    password VARCHAR(20) NULL
) CHARSET = UTF8;

